### ISSUE TITLE
AzureFunctionApp@2 added support for Flex Consumption

### ISSUE THREAD

**Issue by sven5** [erwinkramer/azure-functions-flex-consumption-migration-guide#1]
The AzureFunctionApp@2 pipeline task now supports FC1 plans. 

See doc: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines

**Comment by erwinkramer** [comment]
Thanks i will update this.

**Comment by erwinkramer** [comment]
@sven5 i updated the page based on the documentation. I cannot verify if it also works with the build steps i have written down, as I don't have access to my test setup at the moment. Would you happen to know?

**Comment by erwinkramer** [comment]
I had no succes implementing the original task, and also i stumbled on (slightly related) issues: https://github.com/Azure/azure-functions-host/issues/10714 and https://github.com/Azure/azure-functions-host/issues/10643 .

**Comment by sven5** [comment]
Hi @erwinkramer,
sorry for being late, I was on holidays.

These are my build steps:

```yaml
        steps:          
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build $(buildConfiguration)'
            inputs:
              command: 'build'
              projects: ${{ parameters.buildSolution}}
              arguments: '--configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish $(buildConfiguration)'
            inputs:
              command: publish
              projects: ${{ parameters.buildSolution}}
              publishWebProjects: false
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.artifactStagingDirectory)'
              ArtifactName: '${{ parameters.publishArtifactName }}'
              publishLocation: 'Container'

          - task: AzureFunctionApp@2
            displayName: 'Deploy to Function App'
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              appType: ${{ parameters.appType }}
              resourceGroupName: ${{ parameters.azureResourceGroupName }}
              appName: ${{ parameters.funcName }}
              isFlexConsumption: ${{ parameters.isFlexConsumption }}
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
              
```

The `PublishBuildArtifacts` is optional, we just wanna see the output of the publish step.
